#!/usr/bin/env python3
"""
Example usage of the AURA Framework for ICSE 2025 Artifact Evaluation.

This script demonstrates how to use the AURA framework to evaluate an artifact
based on ICSE 2025 guidelines, using a real artifact JSON generated by Algorithm 2.
"""

import json
import os
from aura_framework import AURAFramework

def main():
    """Main function demonstrating AURA framework usage with a real artifact."""
    print("AURA Framework - ICSE 2025 Artifact Evaluation Example")
    print("=" * 60)
    
    # Path to the artifact JSON generated by Algorithm 2
    artifact_path = "../../algo_outputs/algorithm_2_output/ml-image-classifier_analysis.json"
    if not os.path.exists(artifact_path):
        print(f"Error: Artifact file not found at {artifact_path}")
        return
    print(f"\n1. Using artifact: {artifact_path}")
    
    # Initialize AURA framework
    print("\n2. Initializing AURA framework...")
    try:
        framework = AURAFramework(artifact_path)
        print("   Framework initialized successfully")
    except Exception as e:
        print(f"   Error initializing framework: {e}")
        return
    
    # Evaluate artifact
    print("\n3. Evaluating artifact...")
    try:
        result = framework.evaluate_artifact()
        print("   Evaluation completed successfully")
    except Exception as e:
        print(f"   Error during evaluation: {e}")
        return
    
    # Display results
    print("\n4. Evaluation Results:")
    framework.print_results(result)
    
    # Save results
    print("\n5. Saving results...")
    try:
        framework.save_results(result, "ml_image_classifier_evaluation_results.json")
        print("   Results saved to: ml_image_classifier_evaluation_results.json")
    except Exception as e:
        print(f"   Error saving results: {e}")
    
    # Clean up
    print("\n6. Cleaning up...")
    framework.close()
    
    print("\nExample completed successfully!")
    print("\nTo use with your own artifacts:")
    print("1. Prepare your artifact JSON file (e.g., using Algorithm 2)")
    print("2. Initialize AURA framework with your file path")
    print("3. Call evaluate_artifact() to get results")
    print("4. Use print_results() to display formatted output")

if __name__ == "__main__":
    main() 